### ISSUE TITLE
Access is denied message for egp files on mapped network drive

### ISSUE THREAD

**Issue by raistlin-akira** [kjnh10/saseg_runner#20]
```python
>>> from pathlib import Path
>>> Path('X:\Project.egp')
WindowsPath('X:/Project.egp')
>>> Path('X:\Project.egp').resolve()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\CCK083\Anaconda3\lib\pathlib.py", line 1177, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\CCK083\Anaconda3\lib\pathlib.py", line 205, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
PermissionError: [WinError 5] Access is denied: 'X:\\Project.egp'
```

If using absolute path resolution in run_egp program, it seems to have no errors and egp files can be opened 
```python
>>> import os
>>> os.path.abspath('X:\Project.egp')
'X:\Project.egp'
>>>
```

**Comment by kjnh10** [comment]
Thanks for reporting.

Now I'm investigating.
Could you tell me your python version?

**Comment by kjnh10** [comment]
Could you try to use slash instead of back-slash in the path like below?

run("X:/Project.egp")

**Comment by kjnh10** [comment]
Could you tell me below?
・python version
・minimal code to reproduce

**Comment by raistlin-akira** [comment]
Thanks for the reply. 

Python version
```python
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

To reproduce on Windows:
1. Map a network drive X
2. Create a sample egp (Project.egp) at X with statement '%put Helloworld!'
3. Run the following code
```python
from saseg_runner import run_egp
run_egp(egp_path='X:/Project.egp', profile_name=`{your profile name}`, eg_version='{your eg version}')
```

**Comment by kjnh10** [comment]
X drive is a remote server or link to a local path which is created by subst command?

**Comment by raistlin-akira** [comment]
No. It is from remote server.

My workaround is to copy the egp file from the network to local XD

I think the error is due to that resolving UNC path will require full control to the folder, which causes 'the access denied' error. 

Still, I will suggest using os.path.abspath() to get the complete path for egp file in run_egp(). This will save the need to copy file from network drive to local haha

**Comment by kjnh10** [comment]
I see.Then, is it possible for you to create the pull request?

This module has many points where Path object is used, so I'm not sure that changing Path.resolve() to os.path.abspath() is enough for your case.

you can make your local development environment like below.
```
pip uninstall saseg_runner  # to uninstall the current version
cd <anywhere>
git clone https://github.com/kjnh10/saseg_runner # it's better to fork this project and clone it for making a pull request later.
cd saseg_runner
pip install --editable ./
# you can edit the 'run' function in runner.py
``` 

If it's not, I will try to modify this issue by myself.

**Comment by kjnh10** [comment]
v0.1.13 has been released.
